---
kind: pipeline
type: docker
name: build-dry-run
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - feature/*
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: JqJrmlCUY0OnPbNviRT/k/L1sDcYJwCqsYF8HQjnvWCUINFRhq0l5slNqp+v
---
kind: secret
name: docker_password
data: p9HLpGD0sUCHvyjmn5S/teDfyBB4A8GWuVlEI+QfeSRXlOrLgI8WkWWlnj6d2Kise0phgMYP5dv8vej5u/CmXA==
---
kind: signature
hmac: e878bc5611bcf5810dd22db2e354db8d28164ab9abe6ef5b50a563cdd298e211

...
